[package]
name = "arr_ty"
version = "0.4.0"
authors = ["Nossie531"]
edition = "2024"
description = "Macros for smart array initialization."
repository = "https://github.com/nossie531/arr_ty"
license = "MIT OR Apache-2.0"
keywords = ["macro", "array"]
categories = ["no-std", "rust-patterns"]
